config/routes.rb
Strive::Application.routes.draw do
  devise_for :users
  
  devise_scope :user do
    get "signin", to: "devise/sessions#new"
    get "signup", to: "devise/registrations#new"
    get "signout", to: "devise/sessions#destroy"
  end

  get 'account/schedules' => "schedules#index_for_account"
  get 'account/schedules/get_events' =>"schedules#get_events"
  get 'account/schedules/new' =>"schedules#new_for_account"
  post 'account/schedules/move' =>"schedules#move"
  post 'account/schedules/resize' =>"schedules#resize"
  get 'account/schedules/:id/edit' =>"schedules#edit" 
  delete 'account/schedules/:id' =>"schedules#destroy"

  resources :goals do
    resources :schedules do
      collection do
         get  :calendar
         post :move
         post :resize
         get :get_events
      end
    end
  end

    resources :schedules do
      collection do
         get  :calendar
         post :move
         post :resize
         get :get_events
      end
    end

  get "static_pages/home"

  root 'static_pages#home'

end

app/models/schedule.rb
# == Schema Information
#
# Table name: schedules
#
#  id          :integer          not null, primary key
#  title       :string(255)
#  description :text
#  goal_id     :integer
#  starttime   :datetime
#  endtime     :datetime
#  all_day     :boolean          default(FALSE)
#  status      :integer
#  created_at  :datetime
#  updated_at  :datetime
#  color       :string(255)
#  user_id     :integer
#  done        :boolean          default(FALSE)
#  hours       :float
#

class Schedule < ActiveRecord::Base

	belongs_to :goal
	belongs_to :user

	validates  :user_id , :starttime , :endtime , presence: true

	def self.total_grouped_by_day(start)
		schedules = where(starttime: start.beginning_of_day..Time.zone.now)
		schedules = schedules.group("date(starttime)")
		schedules = schedules.select("starttime, sum(hours) as total_hours")
		#schedules = schedules.select.sum(:hours)
		schedules.group_by { |o| o.starttime.to_date }
		#binding.pry
	end

end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
	include SchedulesHelper

	before_action :login_required 
	
	def index
		if params[:goal_id] != nil 
			@goal = Goal.find(params[:goal_id])
			render "index_for_calendar"
		end		
		get_schedules_data_chart(nil)
		@schedules = current_user.schedules.order(:starttime)
	end

	def index_for_account
	end

	def show
		@schedule = current_user.schedules.find(params[:id])
	end
	def new

		@goal = Goal.find(params[:goal_id])
		@schedule = current_user.schedules.build(:goal_id => params[:goal_id] ,
																			:starttime => params[:starttime] ,
		                                  :endtime => params[:endtime] ,
		                                  :all_day => params[:all_day],
		                                  :hours => '0.5' ,
		                                  :status => '1' )
	  #binding.pry
		render :json => { :form => render_to_string(:partial => 'edit_form') }
	end

	def new_for_account
		@schedule = current_user.schedules.build(
																			:starttime => params[:starttime] ,
		                                  :endtime => params[:endtime] ,
		                                  :all_day => params[:all_day],
		                                  :hours => '0.5' ,
		                                  :status => '1' )
	  #binding.pry
		render :json => { :form => render_to_string(:partial => 'edit_form') }
	end

	def create
		@schedule = current_user.schedules.new(schedule_params)
		#binding.pry

		if @schedule.save
		   render :nothing => true  
	    else
	     render :text => event.errors.full_messages.to_sentence, :status => 422
		end 
	end

	def edit
		
		@schedule = current_user.schedules.find(params[:id])
    render :json => { :form => render_to_string(:partial => 'edit_form') }	
	end

	def update
		@schedule = Schedule.find_by_id(params[:id])
    @schedule.update(schedule_params)
    #binding.pry
		if @schedule.save
			#redirect_to goal_schedules_path(@goal.id)
		  render :nothing => true
	    else
	     render :text => event.errors.full_messages.to_sentence, :status => 422
		end 
	end

	

	def destroy
		@schedule = Schedule.find_by_id(params[:id])
		@schedule.destroy

		render :nothing => true   
	end

	def get_events		
			# if have goal_id , find goal's schedules , else find user's schedules
			
			if params[:goal_id] != nil 
				@goal = Goal.find(params[:goal_id])
	   	  @schedules = @goal.schedules.find(:all, :conditions => ["starttime >= '#{Time.at(params['start'].to_i).to_formatted_s(:db)}' and endtime <= '#{Time.at(params['end'].to_i).to_formatted_s(:db)}'"] )
			else
				@user = current_user
	    	@schedules = @user.schedules.find(:all, :conditions => ["starttime >= '#{Time.at(params['start'].to_i).to_formatted_s(:db)}' and endtime <= '#{Time.at(params['end'].to_i).to_formatted_s(:db)}'"] )
			end

	    schedules = [] 
	    
	    @schedules.each do |schedule|
	    	#if schedule in goal and schedule not has own color ,use goal color
	    	if schedule.goal != nil && schedule.color == nil
	    		schedule_color = schedule.goal.color
	    	else
	    		schedule_color = schedule.color
	    	end
	      schedules << {:description => schedule.description ,:color => schedule_color ,
	      	            :title => schedule.title , :allDay => schedule.all_day ,
	      	            :id => schedule.id, :start => "#{schedule.starttime.iso8601}",
	      	            :end => "#{schedule.endtime.iso8601}" }
	    end
	    #binding.pry
	    render :text => schedules.to_json
	end

  def move
  	@schedule = Schedule.find_by_id(params[:id])
	    if @schedule
	      @schedule.starttime = (params[:minute_delta].to_i).minutes.from_now((params[:day_delta].to_i).days.from_now(@schedule.starttime))
	      @schedule.endtime = (params[:minute_delta].to_i).minutes.from_now((params[:day_delta].to_i).days.from_now(@schedule.endtime))
	      @schedule.save
	    end
	  render :nothing => true
  end

	def resize
	    @schedule = Schedule.find_by_id params[:id]
	    if @schedule
	      @schedule.endtime = (params[:minute_delta].to_i).minutes.from_now((params[:day_delta].to_i).days.from_now(@schedule.endtime))
	      @schedule.hours += (params[:minute_delta].to_f)/60
	      @schedule.save

	    end    
	    render :nothing => true
	end

	private
		def schedule_params
			#params[:user_id] = current_user.id

			params.require(:schedule).permit(:hours,:goal_id,:user_id,:title,:description,:starttime,
				                               :endtime,:status,:all_day,:color,:done)
		end
end

app/helpers/schedules_helper.rb
module SchedulesHelper

	def get_schedules_data_chart(goal)
		
		if goal != nil
			@schedulePresenter = SchedulePresenter.new(:user => current_user , :goal => goal )
		else
			@schedulePresenter = SchedulePresenter.new(:user => current_user )

		end
		
		@chart = @schedulePresenter.chart
		@chart_donut = @schedulePresenter.chart_donut
		@today_schedules = @schedulePresenter.today_data
		@next_week_schedules = @schedulePresenter.next_week_data
		@past_schedules = @schedulePresenter.past_data
		@future_schedules = @schedulePresenter.future_data
		@labels=@schedulePresenter.labels
		@donut_goal_index=@schedulePresenter.donut_goal_index
	end

end

app/views/schedules/_calendar.html.erb
<div></div>
<div>
  <div id='calendar'>
  </div>
</div>
<div id = "desc_dialog" class="dialog" style ="display:none;">
  <div id = "event_desc">
  </div>
  <div id = "event_actions">
    <span id = "edit_event"></span>
    <span id = "delete_event"></span>
  </div>
</div>
<div id = "create_event_dialog" class="dialog" style ="display:none;">
  <div id = "create_event">
  </div>
</div>

<script type="text/javascript" >

authenticity_token = "<%= form_authenticity_token %>"

    var firstHour = new Date().getUTCHours()+8;
    if (firstHour>=24)
      firstHour=firstHour-24;
    // page is now ready, initialize the calendar...
    var calendar = $('#calendar').fullCalendar({
        // put your options and callbacks here
        firstHour: firstHour, 
        selectable: true,
        editable: true,
        header: {
              left: 'prev,next today',
              center: 'title',
              right: 'month,agendaWeek,agendaDay'
        },
        defaultView: 'agendaWeek',
        height: 500,
        slotMinutes: 30,

        loading: function(bool){
              if (bool) 
                  $('#loading').show();
              else 
                  $('#loading').hide();
        },
        select: function(start, end, allDay) {
              createEvent("new event",start,end,allDay);            
        },
        events: "schedules/get_events",
        timeFormat: 'h:mm t{ - h:mm t} ',
        dragOpacity: "0.5",
        eventMouseover: function(calEvent, jsEvent ,view){
          savBg = $(this).css("background-color");
          savClr = $(this).css("color");
          $(this).css({ color:"#ffff00" , backgroundColor:"#000000"});
          $(this).fadeTo('slow',.95);
        },
        eventMouseout: function(calEvent, jsEvent ,view){
          $(this).css({ color:savClr , backgroundColor:savBg});
          $(this).fadeTo('slow',1);
        },
        eventDrop: function(event, dayDelta, minuteDelta, allDay, revertFunc){
                  moveEvent(event, dayDelta, minuteDelta, allDay);
        },
          
        eventResize: function(event, dayDelta, minuteDelta, revertFunc){
                  resizeEvent(event, dayDelta, minuteDelta);
        },
          
        eventClick: function(event, jsEvent, view){
              showEventDetails(event);
        },
        eventRender: function(event, element) { 
            element.find('.fc-event-title').append("<br/>" + event.description); 
        }
    })

    $('#desc_dialog').on('submit', "#event_form", function(event) {
      event.preventDefault();
      $.ajax({
        type: "POST",
        data: $(this).serialize(),
        url: $(this).attr('action'),
        success: refetch_events_and_close_dialog,
        error: handle_error
      });
      function handle_error(xhr) {
        alert(xhr.responseText);
      }
    });
</script>

app/views/schedules/_edit_form.html.erb
<%= simple_form_for [@goal,@schedule] ,:html => { :id => 'event_form' } do |f| %>
<div>
	<%= f.input :title %>
	<%= f.input :description %>
	<%= f.input :done , :as => :boolean %>
	<!--<%= f.input :color , :as => :hidden %>-->
	<%= f.input :goal_id ,:collection => current_user.goals , :include_blank => "(select if none)"%>
	<%= f.input :starttime , :as => :hidden %>
	<%= f.input :endtime , :as => :hidden %>
	<%= f.input :all_day , :as => :hidden %>
	<%= f.input :status , :as => :hidden %>
	<%= f.input :hours , :as => :hidden %>
	<%= f.button :submit , :class => "btn btn-success" %>
</div>
<% end %>

app/views/schedules/index.html.erb
schedule index

<hr>	
<%= link_to('返回', goals_path ,:class => "btn btn-info") %>
<%= render '/common/show_schedules' %>

app/views/schedules/index_for_account.html.erb
<%= link_to_function "返回", "history.back()" ,:class => "btn btn-info"%>
<hr>
<%= render 'calendar' %>

app/views/schedules/index_for_calendar.html.erb
<%= link_to "返回", goal_path(@goal.id) ,:class => "btn btn-info"%>
<hr>
<%= render 'calendar' %>

app/views/schedules/show.html.erb
<hr>	
<%= link_to_function "返回", "history.back()" ,:class => "btn btn-info"%>

<div class="row">
<div class="span4 ">
	<form class="well">
	  <fieldset>
	    <legend><%= @schedule.title %></legend>
	    <label><%= @schedule.description %></label>
	    
	  </fieldset>
	</form>
</div>
</div>