config/routes.rb
Strive::Application.routes.draw do
  devise_for :users
  
  devise_scope :user do
    get "signin", to: "devise/sessions#new"
    get "signup", to: "devise/registrations#new"
    get "signout", to: "devise/sessions#destroy"
  end

  get 'account/schedules' => "schedules#index_for_account"
  get 'account/schedules/get_events' =>"schedules#get_events"
  get 'account/schedules/new' =>"schedules#new_for_account"
  post 'account/schedules/move' =>"schedules#move"
  post 'account/schedules/resize' =>"schedules#resize"
  get 'account/schedules/:id/edit' =>"schedules#edit" 
  delete 'account/schedules/:id' =>"schedules#destroy"

  resources :goals do
    resources :schedules do
      collection do
         get  :calendar
         post :move
         post :resize
         get :get_events
      end
    end
  end

    resources :schedules do
      collection do
         get  :calendar
         post :move
         post :resize
         get :get_events
      end
    end

  get "static_pages/home"

  root 'static_pages#home'

end

app/models/goal.rb
# == Schema Information
#
# Table name: goals
#
#  id          :integer          not null, primary key
#  title       :string(255)
#  description :text
#  user_id     :integer
#  created_at  :datetime
#  updated_at  :datetime
#  color       :string(255)
#

class Goal < ActiveRecord::Base

	has_many :schedules , dependent: :destroy
	belongs_to :owner , :class_name =>"User" , :foreign_key => :user_id

	def editable_by?(user)
		user && user == owner
	end

end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
	include SchedulesHelper
	before_action :login_required , :only => [ :show,:new , :create , :edit , :update , :destroy]

	def index
		#@goals = Goal.all
		@goals = Goal.paginate(:page => params[:page], :per_page => 9)
	end

	def show
		@goal = Goal.find(params[:id])
		@schedules = @goal.schedules.order(:starttime)
		get_schedules_data_chart(@goal)
		
		#binding.pry
		#gon.products = @chart
	end

	def new
		@goal = Goal.new
	end

	def create
		@goal = current_user.goals.build(goal_params)
		@goal.save

		redirect_to goals_path
	end

	def edit
		@goal = current_user.goals.find(params[:id])
	end

	def update
		@goal = current_user.goals.find(params[:id])
		@goal.update(goal_params)
		if @goal.save
			redirect_to goal_path(@goal)
		else
			render :edit
		end
	end

	def destroy
		@goal = current_user.goals.find(params[:id])
		
		@goal.destroy
		redirect_to goals_path

	end

	private 
		
		def goal_params
			params.require(:goal).permit(:title,:description,:user_id,:color)
		end

end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/views/goals/_form.html.erb
<%= simple_form_for(@goal) do |f| %>
	<div>
	  <%= f.input :title , required: true %>
	  <%= f.input :description  , required: true %>
	  <%= f.input :color, as: :minicolors, input_html: {data: {
          minicolors: {theme: :bootstrap, position: :right}}} %>
	  <%= f.button :submit , :class => "btn btn-success"%>
	</div>
<% end %>

app/views/goals/edit.html.erb
<h1>修改目標</h1>
<%= render 'form' %>
<%= link_to('返回', goals_path) %>

app/views/goals/index.html.erb
<h2>Goal index</h2>
<% if user_signed_in? %>
	<%= link_to("新增目標" , new_goal_path ,:class => "btn btn-info")%>
	<%= link_to("月曆表" , account_schedules_path ,:class => "btn btn-info")%>
	<%= link_to("所有計畫表" , schedules_path ,:class => "btn btn-info")%>
<% end %>
<hr>


<%= will_paginate @goals %>

<div class="row">
  <% @goals.each do |goal| %>
		<div class="span4 ">
				<div class="well" style="border-width:3px; border-style:solid;
																	border-color:<%= goal.color %>">
					<%= goal.title %> |
					<%= truncate(goal.description , length: 20)  %>
					<% if current_user && goal.editable_by?(current_user) %> |
						<%= link_to("進入", goal_path(goal.id)) %>
					<% end %>
					<br>
					today <strong><%= SchedulePresenter.new(:user => current_user ,:goal => goal).today_task_num %></strong> todo
				</div>
		</div>
	<% end %>
</div>

app/views/goals/new.html.erb
<h1>新增目標</h1>
<%= render 'form' %>
<%= link_to('返回', goals_path) %>

app/views/goals/show.html.erb
<%= link_to("修改目標", edit_goal_path , :class =>"btn btn-success") %>
<%= link_to("月曆表", goal_schedules_path(@goal.id) , :class =>"btn btn-success") %>
<%= link_to("刪除目標", goal_path(@goal.id) ,method: :delete ,:confirm => "are you sure?")  %>
<hr>	
<%= link_to('返回', goals_path ,:class => "btn btn-info") %>
<%= render '/common/show_schedules'  %>