config/routes.rb
Strive::Application.routes.draw do
  devise_for :users
  
  devise_scope :user do
    get "signin", to: "devise/sessions#new"
    get "signup", to: "devise/registrations#new"
    get "signout", to: "devise/sessions#destroy"
  end

  get 'account/schedules' => "schedules#index_for_account"
  get 'account/schedules/get_events' =>"schedules#get_events"
  get 'account/schedules/new' =>"schedules#new_for_account"
  post 'account/schedules/move' =>"schedules#move"
  post 'account/schedules/resize' =>"schedules#resize"
  get 'account/schedules/:id/edit' =>"schedules#edit" 
  delete 'account/schedules/:id' =>"schedules#destroy"

  resources :goals do
    resources :schedules do
      collection do
         get  :calendar
         post :move
         post :resize
         get :get_events
      end
    end
  end

    resources :schedules do
      collection do
         get  :calendar
         post :move
         post :resize
         get :get_events
      end
    end

  get "static_pages/home"

  root 'static_pages#home'

end

app/views/common/_schedules_data.html.erb
<table class="table table-condensed table-hover">
	<tbody>
		<tr class="warning">
			<td>行程</td>
			<td>描述</td>
			<td>時數(小時)</td>
			<td>開始時間</td>
			<td>結束時間</td>
		</tr>
	<% if custom_schedules != nil%>
		<% custom_schedules.each do |schedule| %>
			<tr>
				<td><%= link_to(schedule.title , schedule_path(schedule)) %></td>
				<td><%= truncate(schedule.description , length: 20) %></td>
				<td><%= (schedule.endtime - schedule.starttime)/3600 %></td>
				<td><%= schedule.starttime.strftime('%Y-%m-%d %H:%M') %></td>
				<td><%= schedule.endtime.strftime('%Y-%m-%d %H:%M') %></td>
			</tr>
		<% end%>
	<% end %>	
	</tbody>
</table>

app/views/common/_show_schedules.html.erb
<div class ="well ">
	<div class ="tabbable">
		<ul class="nav nav-tabs">
			<li class="active"><a href="#tab1_today" data-toggle="tab">Today</a></li>
			<li><a href="#tab2_next_week" data-toggle="tab">Next_Week</a></li>
			<li><a href="#tab3_future" data-toggle="tab">Future</a></li>
			<li><a href="#tab4_past" data-toggle="tab">Past</a></li>
			<li><a href="#tab5_all" data-toggle="tab">All</a></li>
		</ul>
		<div class="tab-content">
			<div class="tab-pane active" id="tab1_today">
					<%= render '/common/schedules_data' , custom_schedules: @today_schedules  %>
			</div>
			<div class="tab-pane" id="tab2_next_week">
					<%= render '/common/schedules_data' , custom_schedules: @next_week_schedules  %>
			</div>
			<div class="tab-pane" id="tab3_future">
					<%= render '/common/schedules_data' , custom_schedules: @future_schedules  %>
			</div>
			<div class="tab-pane" id="tab4_past">
					<%= render '/common/schedules_data' , custom_schedules: @past_schedules  %>
			</div>
			<div class="tab-pane" id="tab5_all">
					<%= render '/common/schedules_data' , custom_schedules: @schedules  %>
			</div>
		</div>
	</div>
</div>



<div class ="well ">	
	<div class ="tabbable">
		<ul class="nav nav-tabs">
			<li class="active"><a href="#tab1_line" data-toggle="tab">Line</a></li>
			<li><a href="#tab2_bar" data-toggle="tab">Bar</a></li>
			<li><a href="#tab3_donut" data-toggle="tab">Donut</a></li>
		</ul>
		<div class="tab-content">
			<div class="tab-pane active" id="tab1_line">
				<%= content_tag :div, "", id: "schedules_chart_line", data: {schedules: @chart , goals: @labels } %>
			</div>
			<div class="tab-pane active" id="tab2_bar">
				<%= content_tag :div, "", id: "schedules_chart_bar", data: {schedules: @chart , goals: @labels} %>
			</div>
			<div class="tab-pane active" id="tab3_donut">
				<%= content_tag :div, "", id: "schedules_chart_donut", data: 
				{schedules: @chart_donut} %>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript" >
	$('.nav-tabs > li ').hover( function(){
        $(this).find('a').tab('show');
   });

	MorrisLine();
	MorrisBar();
	var donut = MorrisDonut();
	if (<%= @donut_goal_index %> != -1 )
		donut.select(<%= @donut_goal_index %>);

</script>