config/routes.rb
Strive::Application.routes.draw do
  devise_for :users
  
  devise_scope :user do
    get "signin", to: "devise/sessions#new"
    get "signup", to: "devise/registrations#new"
    get "signout", to: "devise/sessions#destroy"
  end

  get 'account/schedules' => "schedules#index_for_account"
  get 'account/schedules/get_events' =>"schedules#get_events"
  get 'account/schedules/new' =>"schedules#new_for_account"
  post 'account/schedules/move' =>"schedules#move"
  post 'account/schedules/resize' =>"schedules#resize"
  get 'account/schedules/:id/edit' =>"schedules#edit" 
  delete 'account/schedules/:id' =>"schedules#destroy"

  resources :goals do
    resources :schedules do
      collection do
         get  :calendar
         post :move
         post :resize
         get :get_events
      end
    end
  end

    resources :schedules do
      collection do
         get  :calendar
         post :move
         post :resize
         get :get_events
      end
    end

  get "static_pages/home"

  root 'static_pages#home'

end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="brand" href="#">Strive</a>
      <div class="nav-collapse collapse">
        <ul class="nav">
         <li class="">
            <%= link_to( "Home" , root_path)%>
          </li>
          <li class="active">
            <%= link_to( "Goals" , goals_path)%>
          </li>
        </ul>
        <ul class="nav pull-right">
          <% if user_signed_in? %>
            <li><%= link_to( current_user.name , "#")%></li>
            <li><%= link_to("登出" , signout_path)%></li>
          <% else %>
            <li><%= link_to("登入" , signin_path)%></li>
            <li><%= link_to("註冊" , signup_path)%></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Strive</title>

  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container">
		<%  flash.each  do  | key ,  value |  %>
        <div class="alert alert-<%= key %>"><%= value %></div> 
    <%  end  %>
		
		<%= yield %>
		<%= debug(params) if Rails.env.development? %>
	</div>
	<%= render 'layouts/footer' %>
</body>
</html>